import { StatusBar, StyleSheet } from 'react-native';
import { APPBAR_HEIGHT, screenHeight, screenWidth } from '../../../constants/Dimensions';
import Colors from '../../../constants/Colors';
import { getStatusBarHeight } from 'react-native-iphone-x-helper';

const ChatGroupScreenStyles = StyleSheet.create({
  containerHeader: {
    width: screenWidth,
    height: APPBAR_HEIGHT + getStatusBarHeight(),
    backgroundColor: Colors.tabIconSelected,
  },
  bgShareLocation: {
    backgroundColor: '#F1F0F0',
    padding: screenWidth / 40,
    borderRadius: screenWidth / 30,
    marginTop: 7,
  },
  endLocation: {
    backgroundColor: '#F1F0F0',
    marginVertical: 10,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: screenWidth / 30,
    padding: 10,
  },
  header: {
    flex: 1,
    marginTop: getStatusBarHeight(),
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: screenWidth / 27.43,
  },
  nameGroup: {
    flex: 9,
    fontSize: screenWidth / 16,
    fontWeight: '500',
    color: Colors.white,
    textAlign: 'center',
  },
  seeLocation: {
    backgroundColor: Colors.white,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: screenWidth / 50,
    marginTop: screenWidth / 30,
    borderRadius: screenWidth / 70,
  },
  keyboardAwareScrollView: {
    flex: 1,
    flexDirection: 'column',
    height: screenWidth / 10,
  },
  audioRecording: {
    flex: 0.3,
  },
  cancel: {
    flex: 1,
  },
  shareLocation: {
    height: screenWidth / 10,
    backgroundColor: Colors.tintColor,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: screenWidth / 30,
    marginVertical: screenWidth / 30,
    borderRadius: screenWidth / 50,
  },
  send1: {
    width: screenWidth / 13,
    height: screenWidth / 13,
    borderRadius: screenWidth / 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.tintColor,
    marginTop: screenWidth / 80,
    marginRight: screenWidth / 50,
  },
  bgAudio: {
    backgroundColor: 'red',
    height: screenWidth / 10,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.9,
    marginHorizontal: screenWidth / 25,
    borderRadius: 10,
    marginBottom: screenWidth / 40,
  },
  textAudio: {
    color: Colors.white,
    fontSize: screenWidth / 20,
    fontWeight: 'bold',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: screenWidth / 54,
  },
  containerInput: {
    flex: 1,
    marginLeft: screenWidth/72,
  },
  input: {
    paddingLeft: screenWidth / 30,
    height: screenWidth / 10,
    borderWidth: 1,
    borderColor: Colors.lightgray,
    borderRadius: screenWidth / 20,
    fontSize: screenWidth / 28,
  },
  send: {
    width: screenWidth / 11,
    height: screenWidth / 11,
    borderRadius: screenWidth / 5.5,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.tintColor,
    marginLeft: screenWidth/36,
    marginRight: screenWidth/72,
  },
  iconFooter: {
    width: screenWidth / 10,
    height: screenWidth / 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  microphone: {
    marginRight: screenWidth / 100,
    marginTop: screenWidth / 90,
  },
  message: {
    marginLeft: screenWidth / 36,
    fontSize: screenWidth / 20,
    marginBottom: screenWidth / 72,
  },
  viewUser: {
    marginRight: screenWidth / 36,
    marginTop: screenWidth / 120,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  sub1ViewUser: {
    flex: 0.7,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  viewTextUser: {
    borderRadius: screenWidth / 25,
    backgroundColor: 'rgba(247,189,66,1)',
    flexDirection: 'column',
  },
  txtMessageUser: {
    textAlign: 'right',
    color: '#FFFFFF',
    marginTop: screenWidth / 90,
    marginHorizontal: screenWidth / 45,
    fontSize: 14,
  },
  txtMessageTimeUser: {
    letterSpacing: 0.3,
    textAlign: 'right',
    color: '#FFFFFF',
    marginBottom: screenWidth / 90,
    marginHorizontal: screenWidth / 45,
    fontSize: 8,
  },
  backgroundImageChat: {
    flex: 1,
    flexDirection: 'row',
    // marginVertical: screenWidth / 60,
  },
  imageChat: {
    width: screenWidth / 3.5,
    height: screenWidth / 5,
    marginBottom: 2,
    borderRadius: 5,
    resizeMode: 'cover',
  },
  timeImageChat: {
    textAlign: 'right',
    fontSize: screenWidth / 45,
    marginRight: 2,
    opacity: 0.9,
    marginBottom: screenWidth / 50,
  },
  mainViewFriend: {
    flexDirection: 'column',
    justifyContent: 'center',
  },
  txtNameFriend: {
    marginLeft: screenWidth / 7,
    fontSize: 9,
    color: 'rgba(0, 0, 0, .40)',
  },
  viewFriend: {
    marginLeft: screenWidth / 36,
    marginTop: screenWidth / 120,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  sub1ViewFriend: {
    flex: 0.7,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  viewTextFriend: {
    marginRight: screenWidth / 120,
    width: screenWidth / 12,
    height: screenWidth / 12,
    borderRadius: screenWidth / 24,
    overflow: 'hidden',
  },
  viewMessageFriend: {
    borderRadius: 14,
    backgroundColor: '#F1F0F0',
    flexDirection: 'column',
  },
  txtMessageFriend: {
    textAlign: 'left',
    color: 'rgba(0, 0, 0, 1)',
    marginTop: screenWidth / 90,
    marginHorizontal: screenWidth / 45,
    fontSize: 15,
  },
  txtMessageTimeFriend: {
    letterSpacing: 0.3,
    textAlign: 'right',
    color: 'rgba(0, 0, 0, .40)',
    marginBottom: screenWidth / 90,
    marginHorizontal: screenWidth / 45,
    fontSize: 8,
  },
  timingRecording: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerRecording: {
    flexDirection: 'row',
    paddingHorizontal: screenWidth / 30,
    marginBottom: screenWidth / 40,
  },
  cancleRecording: {
    backgroundColor: 'rgba(128,128,128,0.15)',
    width: screenWidth / 2.2,
    height: screenWidth / 9,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginRight: screenWidth / 60,
  },
  sendRecording: {
    backgroundColor: Colors.tintColor,
    width: screenWidth / 2.2,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: screenWidth / 60,
    marginRight: screenWidth / 60,
  },
  contentCancleRecording: {
    fontSize: screenWidth / 25,
    fontWeight: '600',
  },
  contentSendRecording: {
    fontSize: screenWidth / 25,
    color: Colors.white,
    fontWeight: '600',
  },
  playbackContainer: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: Colors.tintColor,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginLeft: screenWidth / 1.7,
    borderRadius: screenWidth / 5,
    height: screenWidth / 13,
    paddingHorizontal: 10,
    marginBottom: 5,
  },
  playbackContainerReceived: {
    backgroundColor: '#F1F0F0',
    flexDirection: 'row',
    width: screenWidth / 3.5,
    height: screenWidth / 13.5,
    borderRadius: screenWidth / 4,
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  txtTimeRecording: { 
    alignContent: 'center', 
    fontSize: 38,
    marginTop: screenWidth / 50
  },
  separator: {
    width: screenWidth/15,
    height: 2,
    backgroundColor: Colors.lightgray,
    alignSelf: 'center'
  }
});
export default ChatGroupScreenStyles;
